### ISSUE TITLE
Add support for Azure Resource Group tagging 

### ISSUE THREAD

**Issue by ricardolupo** [test-kitchen/kitchen-azurerm#101]
Currently a user cannot tag a resource group created dynamically in a TK run with azurerm

**Comment by JMLayn** [comment]
To expand on this further, the use case for this feature request is to create resource group tagging similar to vm tagging function already included in the driver. We use tagging as a control for a reaper script that will destroy stale resources in Azure.

**Comment by stuartpreston** [comment]
This has been released to Rubygems in kitchen-azurerm 0.14.6
