### ISSUE TITLE
Support Tagging on all resources created

### ISSUE THREAD

**Issue by josh-hetland** [test-kitchen/kitchen-azurerm#103]
We use tagging for billing purposes and are trying to turn on policy enforcement that specific tags be present on all resources.

It looks like there are already empty tags blocks on each of the resources. can it be included on those as well?

**Comment by josh-hetland** [comment]
I also want to just say thank you for your great work

**Comment by stuartpreston** [comment]
@josh-hetland Thanks for the thanks and for raising issues like this. Yes, you probably saw recently we added support for resource group level tags too.  I'd be happy to take a PR that expanded the tags in the template to cover all created in the resource group.  I can't think of a scenario where it would matter that the VM tags are copied to all resources in the resource group so don't think we need the tag_all option.  Thanks for considering it!

**Comment by josh-hetland** [comment]
I've created PR https://github.com/test-kitchen/kitchen-azurerm/pull/105 to expand the application of the tags to all resources.

Two things of note. kitchen-azurerm seems to be broken in the latest version of the chef-workstation (0.2.41). it creates this error when trying to fetch the IP address for display
`Failed to complete #create action: [undefined method `get' for #<Azure::Network::Mgmt::V2017_03_30::NetworkInterfaces:0x000000000d841a68>] on default-centos-74`

Also, the versions of both kitchen-azurerm and azure_mgmt_network are explicitly pinned somewhere within chef-workstation to 0.14.5 and 0.17.4 respectively.

**Comment by stuartpreston** [comment]
Thanks Josh, I've merged this and will get a release out within the next week. The issue with the IP address fetching was fixed in a later azure_mgmt_network and accordingly kitchen-azurerm 0.14.7 has that fix.
