### ISSUE TITLE
Resourcegroup could not be found

### ISSUE THREAD

**Issue by albertvaka** [test-kitchen/kitchen-azurerm#111]
## Environment:

**kitchen-azurerm**: 0.14.8
**test-kitchen**: 2.1.0
Running tests in Windows instances on Azure.
Happens on any version of Windows.

## Scenario:

Kitchen tests on Azure fail sometimes with a `ResourceGroupNotFound error`. 

```
Failed to complete #destroy action: [{
  "message": "MsRestAzure::AzureOperationError: ResourceGroupNotFound: Resource group 'kitchen-myawesomeproject-win2012-azure-20190513T184129' could not be found.",
...
```

Maybe the resource group gets deleted before it should? Or maybe it never got created and it fails silently up until the point it tries to delete it?

When this happens, in the same logs I also see:

```
E, [2019-05-13T19:06:35.859577 #142] ERROR -- Kitchen: ---Nested Exception---
E, [2019-05-13T19:06:35.859591 #142] ERROR -- Kitchen: Class: Kitchen::ActionFailed
E, [2019-05-13T19:06:35.859605 #142] ERROR -- Kitchen: Message: Failed to complete #verify action: [WinRM::WinRMAuthorizationError]
E, [2019-05-13T19:06:35.859620 #142] ERROR -- Kitchen: ----------------------
```

Which might be related.

Any idea of what might be happening?

**Comment by stuartpreston** [comment]
Hi @albertvaka - we do write the name of the Resource Group into the kitchen state file (.kitchen/{instance-name}.yml) close to the start of the process before any deployment has run, sometimes (in the case of a deployment failure) and combined with `kitchen test` proactively running a destroy this will sometimes mean you get the above error. One way to avoid this would be to delete your .kitchen/ folder between runs if you are sure the previous run has deleted the resource group. Unfortunately this is something we cannot do within the tool itself.

**Comment by stuartpreston** [comment]
Please reopen if there any outstanding issues with the driver. Thanks!
