### ISSUE TITLE
Enable HTTP winrm listener if winrm scheme is set to http

### ISSUE THREAD

**Issue by sean-nixon** [test-kitchen/kitchen-azurerm#119]
### Describe the Enhancement:
On Windows VMs, it would be useful if an HTTP listener could be enabled automatically in addition to the HTTPS listener so that it is possible to use the `negotiate` authentication method which is the default winrm transport method. Currently, the bootstrap script only enables an HTTPS listener.

### Describe the Need:
We are trying to use a custom image with Test Kitchen that is built by Packer. Packer by default disables the HTTP listener. We don't necessarily want to enable the HTTP listener with Packer as then it comes enabled by default when deploying VMs from the image. However, we want Test Kitchen to still be able to use the HTTP listener for short-lived non-production test machines. Allowing Test Kitchen to enable the HTTP listener automatically allows it to "just work" with more VM image configurations and Test Kitchen configurations.

### Current Alternative
Enabling the HTTP listener in our base packer build (this may not be what we want however in a final image used by both Test Kitchen and production deployments) or using the `ssl` winrm transport (currently experiencing issues running this in CI/CD)

**Comment by stuartpreston** [comment]
Hi @sean-nixon 

We do not enable the HTTP listener by default and the one in ARM only works with HTTPS. If you want to override the PowerShell that is used to enable the HTTPS listener, you can use the `winrm_powershell_script` parameter and ARM will supply this to the machine for first boot:

https://github.com/test-kitchen/kitchen-azurerm/blob/master/README.md#enabling-alternative-winrm-configurations

**Comment by sean-nixon** [comment]
@stuartpreston Thanks for the quick reply. I totally missed that parameter. That could definitely help us work around this a lot more easily so thank you very much for pointing me in the right direction.

I still think it would be nice to not require overriding the full WinRM configuration and have a default that works with most Test Kitchen WinRM transport configurations. Currently the default script below enables the firewall rule for HTTP but not the listener itself. That almost seems like it was meant to originally, although I haven't looked at the full commit history. Are you opposed to enabling the HTTP listener automatically? It could even be selectively enabled based on the WinRM transport configuration if my understanding of Test Kitchen plugins is correct. In fact, that's probably the ideal way to handle it in my mind at least.

https://github.com/test-kitchen/kitchen-azurerm/blob/master/lib/kitchen/driver/azurerm.rb#L550

**Comment by stuartpreston** [comment]
I don't have an issue enabling the HTTP listener in this script. Are you able to submit a PR?

**Comment by sean-nixon** [comment]
I can try. I created a simple PR for feedback

**Comment by stuartpreston** [comment]
Closed by #121
