### ISSUE TITLE
VM administrator/root password is hard-coded and known to the public internet

### ISSUE THREAD

**Issue by splatteredbits** [test-kitchen/kitchen-azurerm#122]
# Version:

Latest

# Environment:

Windows

# Scenario:

The password for the administrator account created during provisioning is hard-coded and known.  Malicious users could scan known Azure IP addresses for open VMs and use the known credentials to log into the VM while it is up and grab source code or any other potentially sensitive information on the VM.

# Steps to Reproduce:

1. Provision a VM in Azure.
2. Login via RDP with the username "azure", password "P2ssw0rd".

# Expected Result:

I would expect this driver to generate a cryptographically-strong random password for each VM and use that to log in. I would expect this to be stored on my local computer in a known location that I can look at/view if I need to log into the VM to troubleshoot issues.

# Actual Result:

All VMs created by this driver use the same password. This is a security issue.

**Comment by stuartpreston** [comment]
This affected versions 0 to 0.15.1

@splatteredbits Thanks for reporting this. I agree with your comments. Users should have specified their own password but many (most?) left the defaults which leaves the VM open to intrusion when using the default settings. I have submitted a patch which fixes this (the password can be found in the state file and I amended the README to reflect that).

PS - please avoid putting "latest" as the version number - someone in the future will look at this issue not knowing which version you are referring to.
