### ISSUE TITLE
Kitchen create failing with azureusgovernment as azure_environment.

### ISSUE THREAD

**Issue by Vijay8888** [test-kitchen/kitchen-azurerm#140]
# Version:
Kitchen-azurerm 1.0.0
[Version of the project installed]

# Environment: azureusgovernment

[Details about the environment such as the Operating System, cookbook details, etc...]

# Scenario:

We are setting up kitchen using azurerm driver for azureusgovernment for chef cookbooks testing. We tried variables azure_environment: AzureUSGovernment as mentioned in readme file.created credentials file as mentioned in readme file.

We weren’t able to connect us gov cloud using service principal. Kitchen create failing saying couldn’t able to login, please check tenant id, client I’d, client secrete and request:null, response: null. However spn is able to login using az login outside.

We are suspecting that azure endpoint not pointing to azure us government api correctly.

Could you please suggest this issue.

# Steps to Reproduce:

[If you are filing an issue what are the things we need to do in order to repro your problem?]

# Expected Result:

[What are you expecting to happen as the consequence of above reproduction steps?]

# Actual Result:

[What actually happens after the reproduction steps?]

**Comment by Vijay8888** [comment]
After above issue, we have saved credentials file with utf-8 encoding then we have resolved above issue but getting parse error as below,

Failed to complete create action : [ Couldn’t parse line : “[# subscription id]”] on default-ubuntu-1604.

Could you please help us resolve the issue.

Thanks 
Vijay

**Comment by Vijay8888** [comment]
@stuartpreston could you please help on this.

**Comment by Vijay8888** [comment]
Could someone help on this.

**Comment by Vijay8888** [comment]
We unable to login to azureusgovernment with  using this gem.

**Comment by stuartpreston** [comment]
@Vijay8888 Sorry that I did not see this notification sooner. I'm afraid I'm no longer actively working on the project and govcloud support can only be best-effort due to the lack of a test environment. Generically I would look at `kitchen diagnose` and `kitchen <command> -l debug` to see if you can narrow down the cause.

**Comment by ecottom** [comment]
@Vijay8888 what version of chef workstation are you running?  I'm not seeing this error on Chef Workstation version: 20.8.111 which includes ms_rest_azure 0.12.0 which has this fix https://github.com/Azure/azure-sdk-for-ruby/pull/2782 for this issue https://github.com/Azure/azure-sdk-for-ruby/issues/2781 but I was seeing it on chef workstation 0.15.18.

**Comment by StylusEaterChef** [comment]
@Vijay8888 is this still a problem or was it resolved?

**Comment by marcparadise** [comment]
Closing due to no response - @Vijay8888 please reopen this if you find that the issue is still occurring.
