### ISSUE TITLE
Azure VM adminPassword doesn't always meet complexity requirements

### ISSUE THREAD

**Issue by dw185157** [test-kitchen/kitchen-azurerm#142]
# Version:

Latest.  Not defined.

# Environment:

Windows 10.  Standard Chef cookbook.  Standard non-government Azure.

# Scenario:

1. kitchen create [instance]
2. Auto generated adminPassword will not always meet at least 3 of the password complexity requirements, e.g. TDPMaJIlWReMxtmx - this only contains upper/lowercase letters.

# Steps to Reproduce:

1. kitchen create [instance]

# Expected Result:

The VM should be created

# Actual Result:

VM creation fails with message:  `Failed to complete #create action: [{"error"=>{"code"=>"InvalidParameter", "message"=>"The supplied password must be between 8-123 characters long and must satisfy at least 3 of password complexity requirements from the following:\r\n1) Contains an uppercase character\r\n2) Contains a lowercase character\r\n3) Contains a numeric digit\r\n4) Contains a special character\r\n5) Control characters are not allowed", "target"=>"adminPassword"}}] on xxxxxxxxxx`

**Comment by dw185157** [comment]
https://github.com/test-kitchen/kitchen-azurerm/blob/c22b7b605a55c4f7844a08fa7a299e76f57e5906/lib/kitchen/driver/azurerm.rb#L78

Could be changed to method hex with a longer length?

**Comment by StylusEaterChef** [comment]
It can be changed. Is there a particular length you're suggesting that won't run afoul of maximum password sizes?

Would something like this meet your needs?

```     
default_config(:password) do |_config|
    [SecureRandom.base64(12), SecureRandom.alphanumeric(12)].join('')
end
```

**Comment by dw185157** [comment]
Actually, I've just discovered a base64 generator and can replicate the issue: https://generate.plus/en/base64

However, by providing an odd number such as 25 each string has met the criteria, so I'd recommend a base64 length of 25.

**Comment by StylusEaterChef** [comment]
PR was merged for this. @tas50 can we close this issue?
