### ISSUE TITLE
Random failures related to password complexity

### ISSUE THREAD

**Issue by jasonwbarnett** [test-kitchen/kitchen-azurerm#156]
# Version:

kitchen-azurerm v1.0.0

# Environment:

OS: RHEL 7

# Scenario:

reliably spin up a windows VM on Azure using test kitchen

# Steps to Reproduce:

Continue spinning up a windows VM until you get the error shown in actual result

# Expected Result:

The password auto generated by kitchen should meet the complexity requirements of Azure

# Actual Result:

```text
Failed to complete #create action: [{"error"=>{"code"=>"InvalidParameter", "message"=>"The supplied password must be between 8-123 characters long and must satisfy at least 3 of password complexity requirements from the following:\r\n1) Contains an uppercase character\r\n2) Contains a lowercase character\r\n3) Contains a numeric digit\r\n4) Contains a special character\r\n5) Control characters are not allowed", "target"=>"adminPassword"}}] on default-windows-2012r2
```

**Comment by StylusEaterChef** [comment]
@jasonwbarnett I see you're reporting you used kitchen-azurerm (v1.0.0). Are you able to try the same approach with the latest version of kitchen-azurerm (v1.2.0)?

**Comment by jasonwbarnett** [comment]
ahh, I see! you fixed it :)

https://github.com/test-kitchen/kitchen-azurerm/compare/v1.0.0...v1.2.0#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR11

---

I'll test and report back.

**Comment by StylusEaterChef** [comment]
> ahh, I see! you fixed it :)
> 
> [v1.0.0...v1.2.0diff-4ac32a78649ca5bdd8e0ba38b7006a1eR11](https://github.com/test-kitchen/kitchen-azurerm/compare/v1.0.0...v1.2.0diff-4ac32a78649ca5bdd8e0ba38b7006a1eR11)
> 
> I'll test and report back.

Awesome. Looking forward to the feedback.

**Comment by StylusEaterChef** [comment]
@jasonwbarnett mind closing this issue if you're all set? Thanks.
