### ISSUE TITLE
Issue with file

### ISSUE THREAD

**Issue by ElementalDev** [test-kitchen/kitchen-azurerm#165]
I had this issue

>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [uninitialized constant MsRest] on default-win10-adoa
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

And noticed that the azure_credentials.rb does not have the following at the top of the file:

require 'ms_rest'
require 'ms_rest_azure'

I added these to the file manually and it began to work. It seems like a bug to me but im wondering if its intentional.

**Comment by StylusEaterChef** [comment]
Good catch. I was able to recreate this and I think it was due to a recent commit.
