### ISSUE TITLE
Autoload ms_rest and ms_rest_azure Components

### ISSUE THREAD

**Issue by StylusEaterChef** [test-kitchen/kitchen-azurerm#167]
### Describe the Enhancement:

Need to autoload components to help reduce overhead.

### Describe the Need:

Determine what needs to autoload and be more selective than require ms_rest and ms_rest_azure.

### Current Alternative

Yes, it's currently implemented.

### Can We Help You Implement This?:

N/A

**Comment by tas50** [comment]
Paging @mwrock here for help
