### ISSUE TITLE
Username not being added to kitchen state when running test kitchen

### ISSUE THREAD

**Issue by ElementalDev** [test-kitchen/kitchen-azurerm#170]
# Version:

master code (1.3.0)

# Environment:

Windows 10
ChefDK version: 4.11.0
Chef Infra Client version: 15.14.0
Chef InSpec version: 4.22.22
Test Kitchen version: 2.7.1
Foodcritic version: 16.3.0
Cookstyle version: 5.23.0

# Scenario:

Username not being added to state

# Steps to Reproduce:

- Run kitchen command that will spin up a VM 
- Inspect the kitchen state file

# Expected Result:

```yaml
---
<...>
username: azure
<...>
```

# Actual Result:

```yaml
---
<...>
username:
<...>
```

Let me know if theres anything I can do, Happy to help 😄

**Comment by StylusEaterChef** [comment]
Mind adding a patch with a test?

**Comment by ElementalDev** [comment]
I can give it a so, sure. Would you rather me get it into my open PR or just create a new one for this new bit

**Comment by StylusEaterChef** [comment]
> I can give it a so, sure. Would you rather me get it into my open PR or just create a new one for this new bit

New PR. Thanks.

**Comment by StylusEaterChef** [comment]
Fixed. Nice work @ElementalDev.
