### ISSUE TITLE
Failed to open TCP connection to 169.254.169.254:80  azurerm

### ISSUE THREAD

**Issue by jfe7** [test-kitchen/kitchen-azurerm#188]
# Version:  Test Kitchen version 2.8.0

I am trying to spin up a Test Kitchen with azurerm, I am facing the below error, any idea how to fix this please? 

-----> Starting Test Kitchen (v2.8.0)
-----> Creating <default-windows2019>...
       Creating Resource Group: kitchen-default-windows2019-20210120T121246
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [Failed to open TCP connection to 169.254.169.254:80 (A socket operation was attempted to an unreachable network. - connect(2) for "169.254.169.254" port 80)] on default-windows2019
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

No other information is in the log files.

**Comment by marcparadise** [comment]
Thanks for reporting this @jfe7.   Based on the error message: 

```
[Failed to open TCP connection to 169.254.169.254:80 (A socket operation was attempted to an unreachable network. - connect(2) for "169.254.169.254" port 80)]

```

It seems like the host you're trying to connect to can't be reached from the host running `kitchen`. Is there a jump box or VPN that you should be accessing through?

**Comment by jfe7** [comment]
Turns out in the end it was nothing to do with networking, I had been given wrong creds! 

Thanks
