### ISSUE TITLE
Option for post-deployment template

### ISSUE THREAD

**Issue by hbuckle** [test-kitchen/kitchen-azurerm#43]
It would be nice to have an option to apply a post-deploy arm template to do things like add additional disks, VM extensions, NSGs etc.

**Comment by stuartpreston** [comment]
That's an interesting idea, so to be clear you would want the post-deploy arm template to do the same as the pre-deployment template, in the same resource group as the created resources?

**Comment by hbuckle** [comment]
Yes thanks, exactly that - it would be really useful for us to make the test VMs look more like production by applying some post deploy config.

**Comment by stuartpreston** [comment]
I'm parking this one for now as we have lifecycle hooks in Test Kitchen now, see https://github.com/test-kitchen/test-kitchen/blob/00ef30e4b9b0055afd712fa145727431ed628b10/RELEASE_NOTES.md#life-cycle-hooks

**Comment by stuartpreston** [comment]
Released in v0.14.4
