### ISSUE TITLE
Exception thrown when an Azure SubscriptionID cannot be found

### ISSUE THREAD

**Issue by keyrage** [test-kitchen/kitchen-azurerm#47]
The following exception gets thrown when a Azure SubscriptionID is not set as an environment variable in Windows when it is referenced in a kitchen.yml file. Really a warning or human readable error should be thrown instead of an unhandled exception.

----
Failed to complete #create action: [undefined method `[]' for nil:NilClass]

------Backtrace-------
E, [2017-03-16T12:41:28.721357 #15264] ERROR -- Kitchen: C:/Users/se6362/AppData/Local/chefdk/gem/ruby/2.3.0/gems/kitchen-azurerm-0.8.1/lib/kitchen/driver/credentials.rb:30:in `azure_credentials_for_subscription'
E, [2017-03-16T12:41:28.723169 #15264] ERROR -- Kitchen: C:/Users/se6362/AppData/Local/chefdk/gem/ruby/2.3.0/gems/kitchen-azurerm-0.8.1/lib/kitchen/driver/azurerm.rb:98:in `create'

----

**Comment by stuartpreston** [comment]
This will be fixed in the next release 0.14.1

```
-----> Starting Kitchen (v1.21.2)-----> Creating <default-ubuntu-1404>...>>>>>> ------Exception------->>>>>> Class: Kitchen::ActionFailed>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [A subscription_id config value was not detected and kitchen-azurerm cannot continue. Please check your .kitchen.yml configuration. Exiting.] on default-ubuntu-1404
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```
