### ISSUE TITLE
Should not require ~/.azure/credentials

### ISSUE THREAD

**Issue by karstenmueller** [test-kitchen/kitchen-azurerm#48]
The driver should not require the file ~/.azure/credentials. I am using environment variables in for CI, so the credential file is not needed.

-----
sh -c kitchen test -c 1 --destroy=always 
-----> Starting Kitchen (v1.16.0)
WARN: Unresolved specs during Gem::Specification.reset:
      octokit (~> 4.0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
-----> Cleaning up any prior instances of <default-ubuntu-1604>
-----> Destroying <default-ubuntu-1604>...
       Finished destroying <default-ubuntu-1604> (0m0.00s).
-----> Testing <default-ubuntu-1604>
-----> Creating <default-ubuntu-1604>...
/root/.azure/credentials was not found or not accessible.

**Comment by stuartpreston** [comment]
Hi @karstenmueller - I checked the code and this is a "warn" level message.  Can you confirm whether the lack of the file causes an issue besides the warning?

**Comment by karstenmueller** [comment]
Hi @stuartpreston - sorry, you are right. It is a warning only. So I have to look further for the cause of my error;)
