### ISSUE TITLE
[uninitialized constant MsRestAzure::AzureEnvironments::Azure]

### ISSUE THREAD

**Issue by luke-vidler** [test-kitchen/kitchen-azurerm#58]
Getting this error when running 'kitchen-create'. 

Anything obvious?

Mac OSX 10.12.5
CHefDK 1.5.0
kitchen 1.16.0

**Comment by elconas** [comment]
Reason is this commit https://github.com/Azure/azure-sdk-for-ruby/pull/711
in the azure_mgmt_network gem

Release 0.7.0 = OK
Release 0.8.1 = Broken 

To fix it, follow the rename and pin the versions in the gemspec

**Comment by elconas** [comment]
To fix: downgrade ms_rest_azure to 0.7.0 and uninstall other versions.

**Comment by elconas** [comment]
Seems this one fixes it https://github.com/test-kitchen/kitchen-azurerm/pull/59

**Comment by stuartpreston** [comment]
Sorry about that, this was because of a the breaking change in [Azure/azure-sdk-for-ruby#711](https://github.com/Azure/azure-sdk-for-ruby/pull/711) as well as our version pinning strategy being quite open.  This is fixed in kitchen-azurerm version 0.11.0 that is now on RubyGems.
