### ISSUE TITLE
Authenticate via certificate instead of password

### ISSUE THREAD

**Issue by bcolebank** [test-kitchen/kitchen-azurerm#61]
It appears that the AzureRm will not allow using a certificate instead of a password for connecting to Azure to deploy machines.

~/.azure/credentials
[MySubscriptionId]
client_id = "ApplicationIdForMyAzureRunAsAccount"
client_secret = "ThumbprintForMyAzureRunAsAccount"
tenant_id = "TenantIdForMyAzureRunAsAccount"

Log snippet:
E, [2017-08-10T10:43:48.624712 #39524] ERROR -- Kitchen: ---Nested Exception---
E, [2017-08-10T10:43:48.624712 #39524] ERROR -- Kitchen: Class: Kitchen::ActionFailed
E, [2017-08-10T10:43:48.624712 #39524] ERROR -- Kitchen: Message: Failed to complete #create action: [{
  "message": "Couldn't login to Azure, please verify your tenant id, client id and client secret",
  "request": null,
  "response": null
}]

**Comment by stuartpreston** [comment]
Hi - this is correct as far as I understand the underlying SDK does not support providing a certificate thumbprint here.  Do you have a service principal with associated certificate and do you have the steps you took to associate the certificate I can follow to make sure I'm doing the same as you?

**Comment by stuartpreston** [comment]
Closing due to age.  Please reopen if this is a blocker for you.  We still don't have a way of supplying a certificate via the Ruby SDK as far as I'm aware.
