### ISSUE TITLE
undefined local variable when using pre_deployment_template

### ISSUE THREAD

**Issue by mtyler** [test-kitchen/kitchen-azurerm#65]
Running `kitchen converge` with pre_deployment_template results in

undefined local variable or method `post_deployment_name'

Appears to come from this:
https://github.com/test-kitchen/kitchen-azurerm/blob/master/lib/kitchen/driver/azurerm.rb#L215

**Comment by stuartpreston** [comment]
Hi @mtyler this was fixed in 0.12.1 - please update your `kitchen-azurerm` gem and retry. Thanks!
