### ISSUE TITLE
WinRM username and password specified do not work

### ISSUE THREAD

**Issue by stuartpreston** [test-kitchen/kitchen-azurerm#70]
Need to verify the configuration steps in: https://learn.chef.io/modules/local-development/windows/azure/apply-a-cookbook#/ WRT WinRM username and password and update the example or fix the documentation.  Community reports setting username and password underneath `transport` did not have the desired effect and the defaults were used.

**Comment by sh33ner** [comment]
I've been trying to use the winrm transport, and I can't even get the default username and password in the driver to work.

**Comment by tpetchel** [comment]
I maintain the Learn Chef module mentioned above. I discovered that making the password slightly more complex (`L34rnCh3f` => `L34rnCh3f!`) helped get things working. I'll post an update to the module as soon as possible.

As for the default password, it makes sense that it might not work because `P2ssw0rd` does not contain any symbols. 

I don't know what, if anything, has changed in between this Test Kitchen driver and Azure.

**Comment by sh33ner** [comment]
I'll take a look and see if that works.  Thanks!

**Comment by sh33ner** [comment]
@tpetchel I tried using Administrator:L34rnCh3f! in the transport config, and it still failed.

This is transport config I have:
  - name: windowsserver
    driver_config:
      image_urn: MicrosoftWindowsServer:WindowsServer:2016-Datacenter:latest
    transport:
      name: winrm
      elevated: true
      username: Administrator
      password: L34rnCh3f!

**Comment by cheeseplus** [comment]
@sh33ner could you repost/edit that with formatting/code fences so we can see the tabbing? YAML is pretty picky about these things so it might be something like an alignment issue.

**Comment by sh33ner** [comment]
`  - name: windowsserver
    driver_config:
      image_urn: MicrosoftWindowsServer:WindowsServer:2016-Datacenter:latest
    transport:
      name: winrm
      elevated: true
      username: Administrator
      password: L34rnCh3f!

**Comment by tpetchel** [comment]
@sh33ner - I tested against 2012 R2. I don't know 2016's password requirements well enough.

**Comment by stuartpreston** [comment]
@sh33ner Are you still seeing a problem here?  If you could post the entirety of your .kitchen.yml then we can have a look.  One thing I spotted is that the use of `Administrator` as a username for an Azure VM is not permitted (see https://docs.microsoft.com/en-us/azure/virtual-machines/windows/faq#what-are-the-username-requirements-when-creating-a-vm).

**Comment by stuartpreston** [comment]
Closing this due to age, please open a new issue if you're continuing to have problems.
