### ISSUE TITLE
azure subscription id nil for kitchen create

### ISSUE THREAD

**Issue by danielprashanth** [test-kitchen/kitchen-azurerm#72]
I have used kitchen version  0.12.4 , when i tried to create kitchen instance with azure-rm driver , im getting an error saying azure_subscription id is NIL even though i have set my subscription id in environmental variables as well as in credentials file in utf-8 encoding format

**Comment by stuartpreston** [comment]
Sorry for not seeing this sooner, please can you post your kitchen.yml?  Have you created your credentials file in `~/.azure/credentials` ?

**Comment by stuartpreston** [comment]
Closing due to age, please re-test against the latest version and open a new issue with the requested information if you continue to have problems.  Thanks.
