### ISSUE TITLE
Azure limits

### ISSUE THREAD

**Issue by anniehedgpeth** [test-kitchen/kitchen-azurerm#75]
I kept getting this error when running my cookbooks on the Jenkins agent, to which I don't have access to logs. 

```
chef exec kitchen test -c 4 -d always
-----> Starting Kitchen (v1.17.0)
-----> Cleaning up any prior instances of <windows-2012r2-chef12>
-----> Destroying <windows-2012r2-chef12>...
       Finished destroying <windows-2012r2-chef12> (0m0.00s).
-----> Testing <windows-2012r2-chef12>
-----> Creating <windows-2012r2-chef12>...
       Creating Resource Group: kitchen-windows-2012r2-chef12-20180309T221125
-----> Destroying <windows-2012r2-chef12>...
       Azure environment: Azure
       Destroying Resource Group: kitchen-windows-2012r2-chef12-20180309T221125
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #destroy action: [undefined method `post' for nil:NilClass] on windows-2012r2-chef12
>>>>>> ----------------------
```

I later found out it wouldn't provision because I was running up against limits to my subscription, but it would have been nice to get some error logging telling me that. I don't know if that's even possible, but I just thought I'd ask. :)

**Comment by stuartpreston** [comment]
I checked with a couple of people and unfortunately we can't see any way of reporting this.  Unless the message comes back through the ARM API then we can't show the user any info at all.  I'm going to close this for now.
