### ISSUE TITLE
Azure environment no longer sets correct management endpoint

### ISSUE THREAD

**Issue by mrala** [test-kitchen/kitchen-azurerm#79]
It seems the [0.14 release](https://github.com/test-kitchen/kitchen-azurerm/blob/v0.14.0/lib/kitchen/driver/azurerm.rb#L188-L189) does not set the correct management endpoint. It was being set correctly in [0.13 as seen here](https://github.com/test-kitchen/kitchen-azurerm/blob/v0.13.0/lib/kitchen/driver/azurerm.rb#L187-L189).

The `azure_environment` config option in test-kitchen is set to `AzureUSGovernment`, however the management endpoint is being set to `https://management.azure.com/` instead of `https://management.core.usgovcloudapi.net/`

**Comment by stuartpreston** [comment]
Thanks for reporting this.  This will be fixed in the next bugfix release 0.14.1
