### ISSUE TITLE
kitchen-azurerm  to test chef provisioned azure hdinsight cluster

### ISSUE THREAD

**Issue by cognsom** [test-kitchen/kitchen-azurerm#81]
kitchen-azurerm  to test chef provisioned azure hdinsight cluster

Could you please guide in testing chef provisioned azure hdinsight cookbook using kitchen-azurerm

**Comment by stuartpreston** [comment]
That is not an explicit feature of kitchen-azurerm, sorry.  kitchen-azurerm is just a driver that allows you to create VM resources (and other resources - look for `pre_deployment_template` in the readme).  and executing tests from that VM using the specified verifier.  If you can write a cookbook that wraps up everything you need to test your HDInsight instance from a VM then you could use your Azure VM to test it.  If there's something specific that doesn't work with the driver then please open a new issue on this repo highlighting what you've tried and any error messages etc.  Thanks.
