### ISSUE TITLE
Clarity requested around behavior of explicit_resource_group_name

### ISSUE THREAD

**Issue by reijop** [test-kitchen/kitchen-azurerm#84]
In the documentation, you specify that ``` <this> parameters can be used in scenarios where you are provided a pre-created Resource Group```

But one of the steps appears to be to destroy the RG before attempting to create any VM's.  In the case of a specific, assigned RG, how do you recommend I move forward?

In my case, I'd like to create a single resource group and bind a specific functional user as an owner of that RG.  This keeps me from having to open a service account to the subscription as an owner (!)

**Comment by stuartpreston** [comment]
Hi @reijop 
1. You don't need to make the service principal have owner access, contributor access is fine (this will allow the creation and deletion of resource groups from that service principal)

2. Yes, using `kitchen test` the RG would be deleted at some point in the lifecycle depending on the current kitchen state.  You'll have to run the kitchen steps manually in this case, i.e. `kitchen create` `kitchen converge` `kitchen verify` `kitchen destroy`.  These steps can combine to bring the target VM to the right state, so probably `kitchen verify` followed by `kitchen destroy` will be what you need.  You need `kitchen destroy` to ensure we delete all the resources in the resource group correctly.  I hope it's clear why we delete all the resources prior to provisioning new ones.  The deletion is handed off to Azure to manage.  I have not found a reliable way outside of using a Resource Group for deleting all resources within the resource group (which is exactly the intention of a resource group - to manage the lifecycle of resource contained with it).

`explicit_resource_group_name` are still expected to be uniquely named (you can use ERB in the .kitchen.yml) per instance so there no resource collisions (the resources deployed in the RG would collide if deployed to the same RG)

Hope that helps.
