### ISSUE TITLE
Explicitly set resource group is deleted on kitchen destroy

### ISSUE THREAD

**Issue by jcoeltjen** [test-kitchen/kitchen-azurerm#85]
When using the `explicit_resource_group_name` parameter the resource group is used correctly but unfortunately is deleted when `kitchen destroy` is called.
As I use a service principal that only has Contributer permissions on this explicit resource group this is pretty much a deal breaker for me.

I would expect that when I set the resource group explicitly to a pre-created group that this group is not deleted on `kitchen destroy`. Or at least add an option to force this behavior.

**Comment by stuartpreston** [comment]
Can you call kitchen converge` (implies `setup`) and `verify` instead of `kitchen test` as a workaround?  A `destroy_explicit_resource_group` option is a good one, will put it on the backlog.  Thanks.

**Comment by stuartpreston** [comment]
This has been added and released via kitchen-azurerm 0.14.2.  A warning will be generated.  Note that the state file will still be removed when kitchen destroy is executed - this is outside the control of the driver.

```
-----> Starting Kitchen (v1.21.2)
-----> Destroying <default-ubuntu-1404>...
$$$$$$ The :destroy_explicit_resource_group setting value is set to "false" so no resources will be destroyed.
$$$$$$ Remember to manually destroy resources to save costs!
       Finished destroying <default-ubuntu-1404> (0m0.00s).
-----> Kitchen is finished. (0m14.15s)
```

**Comment by jcoeltjen** [comment]
I will try this.
Thank you!

**Comment by jcoeltjen** [comment]
I tried it and it works as documented. But I would propose one change in behavior:

Instead of doing nothing on `kitchen destroy` the `destroy_explicit_resource_group` option should only delete the created contents of the resource group if set to `false`.
But then maybe the name would be confusing. 

Maybe we can even add another option `delete_resource_group_contents` instead.
I will open a new issue for this. Your fix here already helped me a lot!
