### ISSUE TITLE
Issue with azure test-kitchen : Tenant ID cannot be nil

### ISSUE THREAD

**Issue by saivv** [test-kitchen/kitchen-azurerm#97]
I am trying to do kitchen create on AZURE here is my yml file.Also created a .azure/credentials.txt with tenantid clientid and cilentsecret and sunscriptionid. But I am failing with the error tenant ID cannot be null like ::
Error : -----> Creating <default-Windows2012-r2>...
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [Tenant id cannot be nil] on default-Windows2012-r2
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

YML file :::::

---
driver:
  name: azurerm

driver_config:
 subscription_id: '05df4cfd-e1ab-4390-9422-c6b0506b8c06'
 location: 'East US'
 machine_size: 'Standard_DS1_v2'
 explicit_resource_group_name: mychefpoc

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: Windows2012-r2
    driver_config:
      image_urn: MicrosoftWindowsServer:WindowsServer:2012-R2-Datacenter:latest
    transport:
      name: winrm

suites:
  - name: default
    run_list:
      - recipe[SP2013_patching::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:

**Comment by saivv** [comment]
@stuartpreston Hello  do you ever came across this issue ever ???

**Comment by stuartpreston** [comment]
Have you tried renaming your credentials.txt to credentials and make sure it's in UTF-8 format?

**Comment by saivv** [comment]
Yes it is saved in UTF8 format :
[05df4cfd-e1ab-4390-9422-c6b0506b8c06]
client_id = "ae308521-63cf-45cd-b4a6-2d67ec925f5f"
client_secret = "oclNWU7~|wedgUYMG5606+^"
tenant_id = "36da45f1-dd2c-4d1f-af13-5abe46b99921"

**Comment by stuartpreston** [comment]
Don't post your secrets into GitHub - you should delete and recreate your Service Principal immediately.  A stacktrace would be better if you have one?

**Comment by saivv** [comment]
@stuartpreston  Yes I saved it in UTF8 fomat.

**Comment by saivv** [comment]
I tried to save it as credentials no luck its still the same error.

**Comment by stuartpreston** [comment]
DO you have a log file at .kitchen/logs/kitchen.log ?  Does it have a stack trace inside it?

**Comment by saivv** [comment]
Yes it did created a kitchen.log 
[kitchen.log](https://github.com/test-kitchen/kitchen-azurerm/files/2446986/kitchen.log)

**Comment by saivv** [comment]
I also observed in .kitchen/default-Windows2012-r2 its listing my vm name wrongly not sure why even I though I edit it to the right VM name no luck.

**Comment by stuartpreston** [comment]
I would make sure you delete your .kitchen folder, and try again.  You can use:
```
chef exec ruby -e "puts \"#{ENV['HOME']}/.azure/credentials\""
```
And check your credentials file is there...

**Comment by saivv** [comment]
Tried that but it still printing the wrong VM name to this(.kitchen/default-Windows2012-r2) file also should this file have the tenantid in it ??

**Comment by stuartpreston** [comment]
Why is it wrong? The VM name is a composite of the suite name and platform name, so looks correct to me.

Only the credentials file has the tenant_id.  Your kitchen.yml just has the subscription_id.  The credentials file is an inifile.  It is possible there are characters in there preventing access to the tenant_id.  If you move the tenant_id to above the client_id and client_secret lines do you get a different message?

**Comment by stuartpreston** [comment]
Please stop (at) mentioning random people within 60 seconds of posting a message.  Your last message seems completely unconnected to your original issue and I'm trying to parse it.

The message you get from converge is likely that it cannot read the hostname from your state file.  In most cases this is becuase the state file doesn't exist, it was left over from a previously aborted run or that you've changed configuration somehow between create and converge phases.  I don't know where *[Dummy]* comes from, and I don't know what you mean by "adding ResourceID" - these are not Azure terms.  The log output doesn't interact with Azure at all, so I'm wondered if you are in fact past the first issue.

Please post your kitchen.yml and the output from `kitchen-diagnose --all` (like it says in the log output) so we can try and help if we can.

**Comment by saivv** [comment]
I had to mention the other person cuz I saw he was mentioning about that Dummy issue in internet if he ever came across it will save your time :)   
 But any way Resource id I grab from my azure portal like /subscriptions/xxxxxxx/resourceGroups/resource_grp/providers/Microsoft.Compute/virtualMachines/vm_name

o/p of diagnose ::

timestamp: 2018-10-04 16:30:05 UTC
kitchen_version: 1.20.0
plugins:
  driver:
    Dummy:
      class: Kitchen::Driver::Dummy
      version: 1.20.0
      api_version: 2
  provisioner:
    ChefZero:
      class: Kitchen::Provisioner::ChefZero
      version: 1.20.0
      api_version: 2
  transport:
    Winrm:
      class: Kitchen::Transport::Winrm
      version: 1.20.0
      api_version: 1
  verifier:
    Inspec:
      class: Kitchen::Verifier::Inspec
      version: 0.23.1
      api_version: 1
loader:
  process_erb: true
  process_local: true
  process_global: true
  global_config:
  project_config:
    filename: C:/Users/user/Desktop/chef-repo/cookbooks/cookbooknmae/.kitchen.yml
    raw_data:
      driver:
        subscription_id: subidxxxxx
        resource_id: "/subscriptions/subidxxxxx/resourceGroups/resourcegrp_name/providers/Microsoft.Compute/virtualMachines/vm_name"
        location: East US
        machine_size: Standard_DS1_v2
        explicit_resource_group_name: resourcegrp_name
      provisioner:
        name: chef_zero
        always_update_cookbooks: true
      verifier:
        name: inspec
      platforms:
      - name: Windows2012-r2
        driver_config:
          subnet_id: resourcegrp_name-vnet/default
          use_managed_disk: true
        transport:
          name: winrm
      suites:
      - name: default
        run_list:
        - recipe[cookbooknmae::default]
        verifier:
          inspec_tests:
          - test/smoke/default
        attributes:
  local_config:
  combined_config:
    filename:
    raw_data:
      driver:
        subscription_id: subidxxxxx
        resource_id: "/subscriptions/subidxxxxx/resourceGroups/resourcegrp_name/providers/Microsoft.Compute/virtualMachines/vm_name"
        location: East US
        machine_size: Standard_DS1_v2
        explicit_resource_group_name: resourcegrp_name
      provisioner:
        name: chef_zero
        always_update_cookbooks: true
      verifier:
        name: inspec
      platforms:
      - name: Windows2012-r2
        driver_config:
          subnet_id: resourcegrp_name-vnet/default
          use_managed_disk: true
        transport:
          name: winrm
      suites:
      - name: default
        run_list:
        - recipe[cookbooknmae::default]
        verifier:
          inspec_tests:
          - test/smoke/default
        attributes:
instances:
  default-Windows2012-r2:
    platform:
      os_type: windows
      shell_type: powershell
    state_file:
      last_action: create
      last_error: KeyError
      my_id: default-Windows2012-r2-1538670253
    driver:
      explicit_resource_group_name: resourcegrp_name
      kitchen_root: C:/Users/user/Desktop/chef-repo/cookbooks/cookbooknmae
      location: East US
      log_level: :info
      machine_size: Standard_DS1_v2
      name: dummy
      pre_create_command:
      random_failure: false
      resource_id: "/subscriptions/subidxxxxx/resourceGroups/resourcegrp_name/providers/Microsoft.Compute/virtualMachines/vm_name"
      sleep: 0
      subnet_id: resourcegrp_name-vnet/default
      subscription_id: subidxxxxx
      test_base_path: C:/Users/user/Desktop/chef-repo/cookbooks/cookbooknmae/test/integration
      use_managed_disk: true
    provisioner:
      always_update_cookbooks: true
      architecture:
      attributes: {}
      channel: :stable
      checksum:
      chef_client_path: "\\bin\\chef-client.bat"
      chef_omnibus_install_options:
      chef_omnibus_url: https://omnitruck.chef.io/install.sh
      chef_zero_host:
      chef_zero_port: 8889
      client_rb: {}
      clients_path:
      command_prefix:
      config_path:
      cookbook_files_glob: README.*,metadata.{json,rb},attributes/**/*,definitions/**/*,files/**/*,libraries/**/*,providers/**/*,recipes/**/*,resources/**/*,templates/**/*
      data_bags_path:
      data_path:
      debug:
      deprecations_as_errors: false
      download_url:
      downloads: {}
      encrypted_data_bag_secret_key_path:
      enforce_idempotency: false
      environments_path:
      ftp_proxy:
      http_proxy:
      https_proxy:
      install_strategy: once
      json_attributes: true
      kitchen_root: C:/Users/user/Desktop/chef-repo/cookbooks/cookbooknmae
      log_file:
      log_level: auto
      max_retries: 1
      multiple_converge: 1
      name: chef_zero
      named_run_list: {}
      nodes_path:
      platform:
      platform_version:
      policyfile:
      policyfile_path:
      product_name:
      product_version: :latest
      profile_ruby: false
      require_chef_omnibus: true
      retry_on_exit_code:
      - 35
      - 213
      roles_path:
      root_path: "$env:TEMP\\kitchen"
      ruby_bindir: "\\embedded\\bin"
      run_list:
      - recipe[cookbooknmae::default]
      sudo:
      sudo_command:
      test_base_path: C:/Users/user/Desktop/chef-repo/cookbooks/cookbooknmae/test/integration
      wait_for_retry: 30
    transport:
      connection_retries: 5
      connection_retry_sleep: 1
      elevated: false
      endpoint_template: http://%{hostname}:%{port}/wsman
      kitchen_root: C:/Users/user/Desktop/chef-repo/cookbooks/cookbooknmae
      log_level: :info
      max_wait_until_ready: 600
      name: winrm
      password:
      port: 5985
      rdp_port: 3389
      test_base_path: C:/Users/user/Desktop/chef-repo/cookbooks/cookbooknmae/test/integration
      username: administrator
      winrm_transport: :negotiate
    verifier:
      chef_omnibus_root: "/opt/chef"
      command_prefix:
      debug:
      ftp_proxy:
      http_proxy:
      https_proxy:
      inspec_tests:
      - test/smoke/default
      kitchen_root: C:/Users/user/Desktop/chef-repo/cookbooks/cookbooknmae
      log_level: :info
      name: inspec
      root_path: "$env:TEMP\\verifier"
      sudo:
      sudo_command:
      suite_name: default
      test_base_path: C:/Users/user/Desktop/chef-repo/cookbooks/cookbooknmae/test/integration

Kitchen.yml :::
---
driver:
  name: azurerm

driver:
 subscription_id: 'xxxxxxxxxxxxxxxxb8c06'
 resource_id: '/subscriptions/xxxxxxxxxxxxxxxxxx/resourceGroups/resourcegrp_name/providers/Microsoft.Compute/virtualMachines/vm_name'
 location: 'East US'
 machine_size: 'Standard_DS1_v2'
 explicit_resource_group_name: resourcegrp_name

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: windows2012-r2
    driver_config:
      subnet_id: resourcegrp_name-vnet/default
      use_managed_disk: true
    transport:
      name: winrm

suites:
  - name: default
    run_list:
      - recipe[cookbooknmae::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:

**Comment by stuartpreston** [comment]
@saivv I think we helped you out in other avenues so closing this issue.  Please open a new one if you are still stuck, or join us in the Chef Community Slack #azure channel.

**Comment by shyambandi** [comment]
Full error for reference

(C:/Users/.azure/credentials) does not contain tenant_id neither is the AZURE_TENANT_ID environment variable set.
Top level ::CompositeIO is deprecated, require 'multipart/post' and use `Multipart::Post::CompositeReadIO` instead!
Top level ::Parts is deprecated, require 'multipart/post' and use `Multipart::Post::Parts` instead!
