### ISSUE TITLE
Feature request: Support MSI when running in a VM or Azure Cloud Shell

### ISSUE THREAD

**Issue by stuartpreston** [test-kitchen/kitchen-azurerm#98]
Now that Chef Workstation includes Test Kitchen and the Azure driver when running on Azure Cloud Shell, it would be good if we could use an MSI instead of having to provide a service principal in ~/.azure/credentials

**Comment by stuartpreston** [comment]
This will be included with the next release. Thanks again!

**Comment by tas50** [comment]
Shipped in #134
